apiVersion: v1
kind: Pod
metadata:
  name: sharepod1
  labels:
    "sharedgpu/gpu_request": "0.5"

    "sharedgpu/gpu_limit": "1.0"

    "sharedgpu/gpu_model": "Iluvatar-BI-V150"

    "sharedgpu/gpu_mem": "2147483648" 
    
spec:
  schedulerName: xpushare-scheduler

  restartPolicy: Never
  containers:
    - name: pytorch
      image:  corex:with-greatwall
      command: ["sh", "-c", "sleep infinity"]
      imagePullPolicy: Never #IfNotPresent

      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
