apiVersion: v1
kind: Pod
metadata:
  name: task-e
  namespace: default
  labels:
    app: fragmentation-exp
    experiment/task: "E"
    sharedgpu/gpu_request: "0.75"        # 75%
    sharedgpu/gpu_limit: "0.75"
    sharedgpu/gpu_model: "Iluvatar-BI-V150"
    sharedgpu/gpu_mem: "2147483648"
spec:
  restartPolicy: Never
  containers:
    - name: task-e
      image: corex:with-greatwall
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: IX_VISIBLE_DEVICES
          value: "0"                     # 希望最终落到 GPU 0
