apiVersion: v1
kind: Pod
metadata:
  name: task-b
  namespace: default
  labels:
    app: fragmentation-exp
    experiment/task: "B"
    experiment/stateless: "true"
    sharedgpu/gpu_request: "0.5"
    sharedgpu/gpu_limit: "0.5"
    sharedgpu/gpu_model: "Iluvatar-BI-V150"
    sharedgpu/gpu_mem: "2147483648"
spec:
  restartPolicy: Never
  containers:
    - name: task-b
      image: corex:with-greatwall
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: IX_VISIBLE_DEVICES
          value: "1"                     # 迁移后在 GPU 1
