apiVersion: v1
kind: Pod
metadata:
  name: task-f
  namespace: default
  labels:
    app: fragmentation-exp
    experiment/task: "F"
    sharedgpu/gpu_request: "0.5"
    sharedgpu/gpu_limit: "0.5"
    sharedgpu/gpu_model: "Iluvatar-BI-V150"
    sharedgpu/gpu_mem: "2147483648"
spec:
  restartPolicy: Never
  containers:
    - name: task-f
      image: corex:with-greatwall
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: IX_VISIBLE_DEVICES
          value: "2"                     # GPU 2
