# 使用一个轻量级的基础镜像
# (它会自动拉取您 aarch64 架构的版本)
# FROM mirror.baidubce.com/ubuntu:22.04-slim
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/ubuntu:22.04-linuxarm64
ENV XPU_PROVIDER=iluvatar

# 1. 复制您本地已经编译好的二进制文件
#    假设您在 /root/XPUShare 目录下运行 build 命令
COPY bin/xpushare-aggregator /usr/bin/xpushare-aggregator

# 2. 运行命令
CMD ["xpushare-aggregator"]
